---
title: "02-calcMarkers"
author: "Bernie Mulvey"
date: "12/14/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(ggtext)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
# library(SpatialFeatureExperiment)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")
library(parallel)


## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 8,color = "#000000"), axis.title.x = element_text(size = 9,color = "#000000"), axis.text.y = element_text(size = 8,color = "#000000"), axis.title.y = element_text(size =9,color = "#000000"), plot.title = element_markdown(size = 10,hjust=0.5,color = "#000000"), strip.text = element_text(size=11), legend.text = element_text(size=7,color = "#000000"), legend.title = element_text(size=8,hjust=0.5,color = "#000000"),axis.ticks = element_line(linewidth=0.5),panel.grid.major = element_line(linewidth=0.5),panel.grid.minor=element_line(linewidth=0.25),plot.title.position="plot"))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

```{r}
## load marker results from registration wrapper
bsys <- readRDS("processed-data/04_Banksy_clusterings/02-regwrapper_outs_nonHarmoBanksys.RDS")
```

```{r}
setDTthreads(1,restore_after_fork = FALSE)


bsys <- mclapply(bsys,mc.cores=6,FUN=function(x){
  x <- as.data.table(x$enrichment)
  y <- melt.data.table(x,id.vars=c("ensembl","gene"))
  y[,stat:=gsub(variable,pattern="^(t_stat|p_value|logFC|fdr)_.*$",replacement="\\1")]
  y[,clust:=gsub(variable,pattern="^(t_stat|p_value|logFC|fdr)_(.*)$",replacement="\\2")]
  y[,variable:=NULL]
  z <- dcast(y,ensembl+gene+clust~stat,value.var="value")
  return(z)
})

## save this--tis the marker tables
saveRDS(bsys,"processed-data/04_Banksy_clusterings/03-noHarmo_banksys_markertables.RDS")
```

extract putative LC clusters from each cluster set
```{r}
bsy.lcs <- lapply(bsys,function(x){
  y <- x[gene %in% c("DBH","TH","SLC6A2","PHOX2A","PHOX2B","MAOA","MAOB") & fdr<0.1 & logFC>1.5]
  return(y)
})

saveRDS(bsy.lcs,"processed-data/04_Banksy_clusterings/03-noHarmo_banksys_putativeLCclusters.RDS")
```

## how many LC clusters per clustering?
```{r}
nlc <- as.data.frame(unlist(lapply(bsy.lcs,function(x){length(unique(x$clust))})))

## interestingly, the minimally-spatial (that pseudobulks 15 or 30 nearest physical neighbors for cluster labeling) at leid/louv res 1 identifies 2 LC clusts each 
unique(bsy.lcs$clust_M0_lam0_k50_res1_kgeom15$clust)
unique(bsy.lcs$clust_M0_lam0_k50_res1_kgeom30$clust)
# (X13/X15 in both of these)

bsys.sub <- bsys[c("clust_M0_lam0_k50_res1_kgeom15","clust_M0_lam0_k50_res1_kgeom30")]
bsys.sub <- lapply(bsys.sub,function(x){y <- x[clust %in% c("X13","X15")]
return(y)})

## which markers are unique to one of the two clusters in each
bsys.sub2 <- lapply(bsys.sub,function(x){
  uniqg <- x[fdr<0.1&logFC>0,.N,by="gene"][N==1,gene]
  y <- x[gene %in% uniqg&fdr<0.1&logFC>0]
  return(y)
})
```