---
title: "01b-NMFcrossval_WebDivsnseq70-150"
author: "Bernie Mulvey"
date: "02-26-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(RcppML)
library(WeberDivechaLCdata)
library(SingleCellExperiment)
library(scuttle)
library(Matrix)
library(singlet)


## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

## the interesting RCTD findings came out at the "label" level, so we want to recreate those and use that here, including the sort of if-it-was-ne-by-any-definition-its-NE approach to maximize NE cells 
```{r}
#######
lcsn <- WeberDivechaLCdata_singleNucleus()

## determine what hierarchical clustering levels there are
tmpcd <- as.data.table(colData(lcsn),keep.rownames=T)
checklabs <- unique(tmpcd[,.(label,label_merged,label_inhibitory)])
## so the inhibitories are re-clusterings (multiple label_inhibitory per label)
View(checklabs[label_merged!="inhibitory"])
## the other 23 labels (of 30) have single label merged assignments.
## so we will make a cluster hierarchy as follows: cluster_merged > label > label or inhibitory subcluster

# to ensure there's enough LCNE cells for RCTD to work with, change label_merged and then label itself to NE for any cell classified as supervised NE OR unsup. NE
tmpcd[,label_merged:=as.character(label_merged)]
tmpcd[unsupervised_NE==TRUE,label_merged:="NE"]
tmpcd[supervised_NE==TRUE,label_merged:="NE"]

## then, make label a character column of merged_label (parent) and label (granular clust #)
tmpcd[,label:=as.character(label)]
tmpcd[,label:=paste0(label_merged,"_",label)]
## for NE neurons, disregard the granular cluster of origin since we're integrating several definition types now
tmpcd[label_merged=="NE",label:="NE"]

stopifnot(length(unique(tmpcd$label))>length(unique(tmpcd$label_merged)))
colData(lcsn) <- DataFrame(tmpcd,row.names=tmpcd$rn)[colnames(lcsn),]

rm(tmpcd,checklabs)
gc(full=T)
```

```{r}
### we need logcounts on here to perform NMF
lcsn <- scuttle::computeLibraryFactors(lcsn)
lcsn <- scuttle::logNormCounts(lcsn)

## run it with a lower tol.  
options(RcppML.threads=11)
options(RcppML.verbose=TRUE)
setDTthreads(1,restore_after_fork=FALSE) # prevent resource competition
crossval <- RcppML::crossValidate(logcounts(lcsn),k=seq(70,150,5),tol=1e-5,threads=11,alpha=0,verbose=T)


saveRDS(crossval, "processed-data/09_snSeqLabelTransfer/01b-Crossval_webdivSnseqNMF_70to150.RDS")

library(ggplot2)
png("plots/09_snSeqLabelTransfer/01b-WebdivSnseqNMF_crossval_k70to150.png", height=4,width=8, unit="in",res=300)
ggplot(crossval,aes(x=k,y=value))+geom_point()+scale_x_continuous(breaks=seq(20,80,10))
dev.off()
```

```{r}
sessionInfo()
```