---
title: "07b-Make_WebDiv_xferdlabel_lut"
author: "Bernie Mulvey"
date: "02-28-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(SpatialExperiment)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

```{r}
xfr <- readRDS("processed-data/05_LabelTransfer/07-WebDivToXen_NMFlabelxfer_tol1e8_k66_alph0.RDS")

xfr2 <- lapply(xfr$targets,function(x){
  y <- as.data.table(cbind(colnames(x),as.character(x$nmf_preds)))
  return(y)
})
xfr2 <- rbindlist(xfr2)
setnames(xfr2,c("rn","WebDivLabel"))
fwrite(xfr2,"processed-data/05_LabelTransfer/07b-WebDivToXen_xferedlabels.txt",sep='\t',quote=F,row.names=F,col.names=T)
```