---
title: "05-NMFlabeltransfer_VisToXen"
format: html
date: 2026-01-26
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(ggtext)
library(gridExtra)
library(SpatialExperiment)
# library(SpatialFeatureExperiment)

## rstudio GUI tweaks
# require(colorout)
# ColorOut()
options('styler.addins_style_transformer' = 'biocthis::bioc_style()')
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn='')
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost='localhost')

## one time install: github cindyfang70/spaTransfer and dependency zdebruine/singlet and up to date zdebruine/RcppML
# devtools::install_github('zdebruine/RcppML')
# devtools::install_github('zdebruine/singlet')
# devtools::install_github('cindyfang70/spaTransfer')
library(nmfLabelTransfer)

## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 8,color = '#000000'), axis.title.x = element_text(size = 9,color = '#000000'), axis.text.y = element_text(size = 8,color = '#000000'), axis.title.y = element_text(size =9,color = '#000000'), plot.title = element_markdown(size = 10,hjust=0.5,color = '#000000'), strip.text = element_text(size=11), legend.text = element_text(size=7,color = '#000000'), legend.title = element_text(size=8,hjust=0.5,color = '#000000'),axis.ticks = element_line(linewidth=0.5),panel.grid.major = element_line(linewidth=0.5),panel.grid.minor=element_line(linewidth=0.25),plot.title.position='plot'))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace('datasets')
```

load Visium data with final labels
```{r}
lcv <- readRDS("../LFF_spatial_LC/processed-data/06-countsOnly_noImgData_QCed_SPE_split_to_tissSections.RDS")

vdom <- readRDS("../LFF_spatial_LC/processed-data/07_featureSelection_dimred_harmony_clustering/04-Initial_louvLeid_res0.5-1-2_clusterings.RDS")
vdom <- vdom$HARMONYlmbna_HDG_SVG_2575
vdom <- vdom[,.(rn,snnHARMONYlmbna_HDG_SVG_2575_louv_res1)]
setnames(vdom,2,"clusid")

vanno <- fread("../LFF_spatial_LC/processed-data/08_validitycheck_25hdg75svg_louv1/10-25hdg75svg_louv1_annots.txt")
vdom <- merge.data.table(vdom,vanno[,.(clusid,anno)],by="clusid")
vdom <- DataFrame(vdom,row.names=vdom$rn)[colnames(lcv),]

colLabels(lcv) <- vdom$anno

rm(vdom,vanno)

unique(lcv$brnum)
lcv$brnum[lcv$brnum=="Br6119(re-dis)"] <- "Br6119"
## drop donors with limited LC and br 1691 (tentatively dropping from Xenium)
lcv <- lcv[,!(lcv$brnum %in% paste0("Br",c(1691,5517,5276,5712)))]


### we need logcounts on here to perform NMF
lcv <- scuttle::logNormCounts(lcv)
```

load xenium data
```{r}
lcx <- readRDS("processed-data/00_prelim_procdat_BJM/02_QC/02b-spe_filtered_genetargonly_log-and-nonlog-norms.RDS")
unique(lcx$brnum) # donor WITH hemisphere
lcx$donor <- lcx$brnum
lcx$donor[lcx$donor=="Br2305L"] <- "Br2305"
lcx$donor[lcx$donor=="Br1039L"] <- "Br1039"
lcx$donor[lcx$donor=="Br5854L"] <- "Br5854"

stopifnot(all(unique(lcx$donor) %in% unique(lcv$brnum)))
stopifnot(all(unique(lcv$brnum) %in% unique(lcx$donor)))

## isoforms of XBP1 are separate probes for xenium, so we want to add a row that just aggregates the two. we recalculate logcounts during the per-sample loop below anyhow so we can get rid of the normalized counts in the xenium SPE too.
assays(lcx)[[3]] <- NULL
assays(lcx)[[2]] <- NULL
gc(full=T)

```

## add a row for XBP1 gene level to rowData and counts, remove isoforms
```{r}
newg <- as.data.frame(rowData(lcx))
newg[(nrow(newg)+1),"Symbol"] <- "XBP1"
rownames(newg)[nrow(newg)] <- "XBP1"
newg <- as.data.table(newg,keep.rownames=T)
newg[rn=="XBP1",ID:="ENSG00000100219"]
newg[rn=="XBP1",Type:="Gene Expression"]
set(newg,i=nrow(newg),j = c(5:12),value=FALSE)
newg <- newg[!(rn %in% c("XBP1u","XBP1s"))]
newg <- DataFrame(newg,row.names=newg$rn)
newg$rn <- NULL

## remove isoforms from counts matrix
newr <- t(as.matrix(colSums(counts(lcx)[c("XBP1s","XBP1u"),],na.rm=T)))
newct <- as(rbind(as.matrix(counts(lcx)),newr),"dgCMatrix")
rownames(newct)[nrow(newct)] <- "XBP1"
newct <- newct[!(rownames(newct) %in% c("XBP1u","XBP1s")),]

## make sure we have the same genes in both of these matrices, in the same order by row and col
stopifnot(all(rownames(newct)==rownames(newg)))
stopifnot(all(colnames(newct)==colnames(lcx)))

lcx2 <- SpatialExperiment(colData=colData(lcx),rowData=newg,assays=list(counts=newct),spatialCoords = spatialCoords(lcx))

rm(lcx,newct,newg,newr)
gc(full=T)
```

## nmf projection is done using the entire visium dataset per xenium SAMPLE (encoded in brnum, which encodes one tissue section as unique donor-hemisphere in this dataset). using Cindy's implementation of this from https://github.com/LieberInstitute/spatialDLPFC_SCZ_XENIUM/blob/devel/code/analysis/04_label_transfer/01_run_spaTransfer.R

```{r}
lcxes <- lapply(unique(lcx2$brnum),function(x){
    lcx2[,lcx2$brnum==x]
})
names(lcxes) <- unique(lcx2$brnum)
lcxes <- lapply(lcxes,scuttle::logNormCounts)

rm(lcx2)
gc(full=T)
### 

# technicalVarName should be the sample identifier in the source(reference) dataset.
# use tol 1e-9 (vs default 1e-5) for higher stringency (passed to nmfLabelTransfer::run_nmf)
# use k=100 for 100 nmf factors
# use 8 threads
vis_to_xen <- transfer_labels(targets = lcxes,source = lcv,assay = "logcounts",annotationsName = "label",technicalVarName = "sample_id",seed = 42,tol=1e-9,k=100,threads=8)

```