---
title: "01-DomainwiseDE_LCasOverriding"
author: "Bernie Mulvey"
date: "02-24-2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(SpatialExperiment)
library(dreamlet)
library(limma)
library(edgeR)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

```{r}
xlc <- readRDS("processed-data/02_QC/02b-spe_filtered_genetargonly_log-and-nonlog-norms.RDS")

lcdom <- fread("processed-data/05_LabelTransfer/04")

tmpcd <- as.data.table(colData(xlc),keep.rownames=T)
tmpcd <- merge.data.table(tmpcd,lcdom,by="rn")

## keep label UNLESS its an intra-LC domain cell, in which case it becomes LC.
tmpcd[,LCdomain_0536:=ifelse(LCdomain_0536=="LC", "LC", nmfpred)]
tmpcd[,LCdomain_1028:=ifelse(LCdomain_1028=="LC", "LC", nmfpred)]
tmpcd[,LCdomain_1520:=ifelse(LCdomain_1520=="LC", "LC", nmfpred)]
tmpcd[,APOE_simple:=ifelse(APOE %in% c("E4het","E4hom"),"E4","E2")]
tmpcd <- DataFrame(tmpcd,row.names=tmpcd$rn)[colnames(xlc),]
tmpcd$rn <- NULL

colData(xlc) <- tmpcd
rm(lcdom,tmpcd)
```

pseudobulk with dreamlet:
```{r}
setDTthreads(1,restore_after_fork = FALSE)

unfilt.unnorm.pbulkDGEs <- lapply(c("LCdomain_0536","LCdomain_1028","LCdomain_1520"),function(d){
  ag <- dreamlet::aggregateToPseudoBulk(xlc,assay="counts",sample_id="brnum",cluster_id = d,BPPARAM = MulticoreParam(8))
  
  # sample metadata for DGELIST:  
  agcd <- as.data.table(colData(ag),keep.rownames=T)
  agcd <- as.data.frame(agcd)
  rownames(agcd) <- agcd$rn
  agcd$rn <- NULL
  
  
  ## only retain clusters when present in at least N= the smallest of the E2/E4, sex, or ancestry groupings (E2=11, EA=10, female = 10, so 10) samples are available after pseudobulking+filtering through dreamlet AND have at least 2,000 pseudobulked counts for the cluster of interest (or normalization and low-expression filtering gets to be impossible):
  ## oligo_neuron will never pass-- < 200 total counts across this cell type in all samples
  ### interestingly, ACHE_SERT_LC_WM only hits a threshold over 1k in a few donors--possibly these cells get roped into LC neurons based on NM seg? tbd.
  ag <- as.list(assays(ag))
  agc <- lapply(ag,FUN=function(a){ncol(a[,colSums(a)>2000])})
  
  # drop assays not meeting threshold
  ag <- ag[!(agc<10)]
  
  ## drop cases where there's insufficient samples (let's say, less than 25% in either binary group)  
  agsc <- lapply(ag,FUN=function(a){
    cn <- colnames(a[,colSums(a)>2000])
    
    tmp <- as.data.table(agcd[cn,])
    if(nrow(tmp[,.N,by="Sex"][N<(0.25*length(cn))])>0){
      ret1 <- 0} else {ret1 <- 1}
    if(nrow(tmp[,.N,by="APOE_simple"][N<(0.25*length(cn))])>0){
      ret2 <- 0} else {ret2 <- 1}
    if(nrow(tmp[,.N,by="Ancestry"][N<(0.25*length(cn))])>0){
      ret3 <- 0} else {ret3 <- 1}
  
    
    if((sum(ret1,ret2,ret3))<3){
      ret<-0
    } else {ret <- 1}
    if(is.null(cn)){ret <- 0}
    return(ret)
  })
  
  ag <- ag[agsc==1]
  
  ## make DGElists for remaining clusters
  dgels <- lapply(ag,FUN=function(a){
  # filtering for 2,000 counts minimum as above
    X <- a[,colSums(a)>20000]
    s <- copy(agcd)[colnames(X),]
    
    dge <- DGEList(counts=as.matrix(X),samples=s)

   return(dge)
  })
  names(dgels) <- names(ag)
  
  return(dgels)
})
names(unfilt.unnorm.pbulkDGEs) <- c("LCdomain_0536","LCdomain_1028","LCdomain_1520")
saveRDS(unfilt.unnorm.pbulkDGEs,"processed-data/06_DomainDE/01a-unfilt_unnorm_pbulk_domain_DGElists_2kctsampmin.RDS")
```