---
title: "SF-XeniumLCdomain_Pbulks_AncStratAPOEdeBoxplots.Rmd"
format: html
author: "Bernie Mulvey"
date: "07-11-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(ggtext)
library(gridExtra)
library(SpatialExperiment)
# library(SpatialFeatureExperiment)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options('styler.addins_style_transformer' = 'biocthis::bioc_style()')
##

## >= and <= comparators that account for floating point error
greaterOrEqual <- function(x,y) {
precision <- sqrt(.Machine$double.eps)
(x >= y) | (abs(x-y) <= precision)
}

lessOrEqual <- function(x,y){
precision <- sqrt(.Machine$double.eps)
(x <= y) | (abs(x-y) <= precision)}

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn='')
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost='localhost')


## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 8,color = '#000000'), axis.title.x = element_text(size = 9,color = '#000000'), axis.text.y = element_text(size = 8,color = '#000000'), axis.title.y = element_text(size =9,color = '#000000'), plot.title = element_markdown(size = 10,hjust=0.5,color = '#000000'), strip.text = element_text(size=11), legend.text = element_text(size=7,color = '#000000'), legend.title = element_text(size=8,hjust=0.5,color = '#000000'),axis.ticks = element_line(linewidth=0.5),panel.grid.major = element_line(linewidth=0.5),panel.grid.minor=element_line(linewidth=0.25),plot.title.position='plot'))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace('datasets')
```


Supp boxplots: All smoothed ISS domain-level, ancestry-strat e2-e4 results as cleaning y boxplots
```{r}
srtdomde <- readRDS("processed-data_newseg/08_VisXferDomainDE/02-voomLmFit_objs_and_DE_tables_LabSex_LabE2vE4_LabSingleGenos_LabAnces_LabAncesE4E2_LCdoms_andOtherXferedVisLabels.RDS")
wddomde <- readRDS("processed-data_newseg/05_snSeqxferDomainDE/02-voomLmFit_objs_and_DE_tables_LabSex_LabE2vE4_LabSingleGenos_LabAnces_LabAncesE4E2_LCdomainAndOtherLabelsXfered.RDS")

domde <- c(srtdomde,wddomde)
pbulks <- lapply(domde,function(x){
  y <- x$YRIAPOlabel$voomLFt$EList$E
  keepn <- grep(colnames(y),pattern="^LC_Br",value=T)
  y <- y[,keepn]
  return(y)
})

sampinf <- lapply(domde,function(x){
  y <- x$YRIAPOlabel$dgel$samples
  keepn <- grep(rownames(y),pattern="^LC_Br",value=T)
  y <- y[keepn,]
  return(y)
})

### now each of these are set up for jaffelab::cleaningy. for accurate fit, include all label-ancestry combinations and extract the LC ones after.
names(pbulks) <- c("SRT Transfer,<br>k1=0.08, k2=0.426","SRT Transfer,<br>k1=0.12, k2=0.199","SRT Transfer,<br>k1=0.16, k2=0.119","SRT Transfer,<br>k1=0.20, k2=0.079","snRNA-seq Transfer,<br>k1= 0.08, k2=0.492","snRNA-seq Transfer,<br>k1=0.12, k2=0.412")

adjpbulks <- mapply(p=pbulks,s=sampinf,n=names(pbulks),SIMPLIFY=FALSE,function(p,s,n){
  s$lab_APOE_PredomAnces <- factor(s$lab_APOE_PredomAnces,levels = unique(s$lab_APOE_PredomAnces))
  s$Sex <- factor(s$Sex)
  s$Age <- as.numeric(s$Age)
  
  p <- p[,rownames(s)]

  modmat <-  model.matrix(~0+lab_APOE_PredomAnces+Age+Sex,data = s)
  degs <- jaffelab::cleaningY(p,modmat,5) # correct for terms that arent in the ancestry-label groupings (term 1 intercept, 2,3,4,5 levels of lab_APOE_ancest, 6 Age, 7 Sex)
  rownames(degs) <- rownames(p)
  colnames(degs) <- colnames(p)
  degs <- as.data.table(degs,keep.rownames=T)
  setnames(degs,"rn","gene")
  return(degs)
})
```

sup figs: all 6 domain defs per gene
```{r}
domdesupplts <- function(pltg="PLPP3"){
  retplts <- mapply(a=adjpbulks,s=sampinf,n=names(adjpbulks),SIMPLIFY=FALSE,function(a,s,n){
  # melt, get gene of interest, append metadata for plotting 
    b <- melt.data.table(a,id.vars="gene")
    b[,variable:=as.character(variable)]
    b <- b[gene==pltg&variable %in% grep(variable,pattern="LC_Br",value=T)]
    b[,titleg:=paste0("*",gene,"*")]
    
    # drop existing rn from sample table if present
    s$rn <- NULL
    s2 <- as.data.table(s,keep.rownames=T)
    s2[,YRIcat:=ifelse(YRIcat=="YRI","AA","EA")]
    b <- merge.data.table(b,s2,by.x="variable",by.y="rn")

    b[,lab_APOE_PredomAnces:=gsub(lab_APOE_PredomAnces,pattern="^LC_",replacement="")]
    b[,lab_APOE_PredomAnces:=gsub(lab_APOE_PredomAnces,pattern="_",replacement=" ")]
    b[,lab_APOE_PredomAnces:=gsub(lab_APOE_PredomAnces,pattern="YRI",replacement="AA")]
    b[,lab_APOE_PredomAnces:=gsub(lab_APOE_PredomAnces,pattern="CEU",replacement="EA")]
    b[,lab_APOE_PredomAnces:=factor(lab_APOE_PredomAnces,levels=c("E2 AA","E4 AA","E2 EA","E4 EA"))]
    plt <- ggplot(b,aes(x=lab_APOE_PredomAnces,y=value,fill=YRIcat))+
      geom_boxplot(outlier.size = 0.4)+
      labs(x="Ancestry",y=paste0("*",unique(b$gene),"* expression in LC Domain<br>(Age and Sex adjusted)"),fill="Predominant\nAncestry")+
      ggtitle(n)+
      theme(
        axis.title.x=element_text(size=8),
        axis.title.y=element_markdown(size=8),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.text = element_markdown(size=7,margin=margin(0,0,0,0,"in")),
        legend.title=element_text(size=7,hjust=0.5),
        legend.background = element_blank(),
        legend.box = element_blank(),
        legend.box.spacing = ggplot2::unit(0,"in"),
        #legend.key = element_blank(),
        legend.key.height=ggplot2::unit(0.0125,"in"),
        legend.key.width=ggplot2::unit(0.0125,"in"),
        legend.key.spacing.y = ggplot2::unit(0.04,"in"),
        title=element_markdown(size=9,hjust=0.5))
        # legend.position.inside = c(0.19,0.165),
        # legend.position="inside")

    return(plt)
  })
  return(retplts)
}


PLPplts <- domdesupplts(pltg="PLPP3")
NTSRplts <- domdesupplts(pltg="NTSR2")
FGFRplts <- domdesupplts(pltg="FGFR3")
## with either of these, just clean up in illustrator to have one legend, one y label
pdf("plots_newseg/manuscript/SuppFigs/PLPP3_LCdomPbulks_byApoAnc.pdf",height=4,width=6.75)
do.call("grid.arrange",c(PLPplts,nrow=2))
dev.off()

pdf("plots_newseg/manuscript/SuppFigs/NTSR2_LCdomPbulks_byApoAnc.pdf",height=4,width=6.75)
do.call("grid.arrange",c(NTSRplts,nrow=2))
dev.off()

pdf("plots_newseg/manuscript/SuppFigs/FGFR3_LCdomPbulks_byApoAnc.pdf",height=4,width=6.75)
do.call("grid.arrange",c(FGFRplts,nrow=2))
dev.off()
```
